[project]
name = "pi-eink-endpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "happo31", email = "happo31@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
pi-eink-endpoint = "pi_eink_endpoint:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
